In [53]:
import pandas as pd
import math
import numpy as py
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression 
from sklearn.model_selection import train_test_split
from datetime import datetime as d
import matplotlib.pyplot as wl
from matplotlib import style

In [54]:
price_data=pd.read_csv('F:/Final_Project/Course_Study/Time_series_dataset/prices.csv') 
price_data.head()

date symbol       open      close        low       high   volume
0  04-01-2010      A  22.453504  22.389128  22.267525  22.625180  3815500
1  05-01-2010      A  22.324749  22.145923  22.002861  22.331903  4186000
2  06-01-2010      A  22.067240  22.067240  22.002861  22.174536  3243700
3  07-01-2010      A  22.017168  22.038626  21.816881  22.045780  3095100
4  08-01-2010      A  21.917024  22.031474  21.745350  22.067240  3733900

In [4]:
#df1=df.loc[:,('date','close', 'open','high','volume')] 

#dfmi['one'] selects the first level of the columns and returns a DataFrame that is singly-indexed. Then another python operation dfmi_with_one['second'] selects the series indexed by 'second' happens. This is indicated by the variable dfmi_with_one because pandas sees these operations as separate events. e.g. separate calls to __getitem__, so it has to treat them as linear operations, they happen one after another.

#Contrast this to df.loc[:,('one','second')] which passes a nested tuple of (slice(None),('one','second')) to a single call to __getitem__. This allows pandas to deal with this as a single entity. Furthermore this order of operations can be significantly faster, and allows one to index both axes if so desired.

In [5]:
#df1['HL_PCT']= (df['high']-df['close'])/df['close'] * 100.0 #Calculate High-Low Percentage
#df1['PCT_change']= (df['close']-df['open'])/df['open'] * 100.0 #Calculate Percent change 

In [6]:
#df2=df1.loc[:,('date','close','HL_PCT','PCT_change','volume')] #features 

In [57]:
price_data=price_data.loc[price_data['symbol'] == 'AMG']
print(price_data.head())

             date symbol       open      close        low       high  volume
54654  04-01-2010    AMG  67.959999  68.879997  67.879997  69.059998  306100
54655  05-01-2010    AMG  68.779999  69.430000  68.269997  69.500000  324600
54656  06-01-2010    AMG  69.209999  70.790001  69.209999  71.470001  486200
54657  07-01-2010    AMG  70.449997  70.470001  69.970001  71.040001  434000
54658  08-01-2010    AMG  70.040001  69.820000  69.309998  70.690002  382800


In [59]:
'''forecast_col = 'close' #Create a forecast on the close column. This is just a variable.
df1.fillna(-9999, inplace=True) #Replace NaN data with this value rather than getting rid of the data

forecast_out= int(math.ceil(0.01* len(df1))) #we want to forecast tomorrow's value. That's why use 0.01. Use Math lib
print(forecast_out)

df2['label']=df1[forecast_col].shift(-forecast_out) #each label will shift by 1 upwards so that close value will be a future value
df2.head()'''

forecast_col = 'close'
df.fillna(value=-99999, inplace=True)
forecast_out = int(math.ceil(0.01 * len(price_data)))
print(forecast_out)
df['label'] = df[forecast_col].shift(-forecast_out)

18


In [60]:
#df2.dropna(inplace=True)
print(df.head())

        date symbol       open      close        low       high   volume  \
0 2010-01-04      A  31.389999  31.300001  31.130000  31.630001  3815500   
1 2010-01-05      A  31.209999  30.960001  30.760000  31.220001  4186000   
2 2010-01-06      A  30.850001  30.850001  30.760000  31.000001  3243700   
3 2010-01-07      A  30.780001  30.809999  30.500000  30.820001  3095100   
4 2010-01-08      A  30.640000  30.800000  30.399999  30.850001  3733900   

       label  
0  28.030000  
1  29.130001  
2  29.500000  
3  29.540000  
4  29.070000  


In [42]:
'''X= np.array(df2.drop(['label','date','symbol'],1)) #X = features 
X= preprocessing.scale(X)
X_lately = X[-forecast_out:]
X = X[:-forecast_out]
df.dropna(inplace=True)'''
#X = np.array(df.drop(['label'], 1))

#X=np.array(df.drop(['label','symbol','date'],axis=1))
#X=df.drop(['label','symbol','date'],1)
X=py.array(df.drop(['label','symbol','date'],axis=1))
X = preprocessing.scale(X)
X = X[:-forecast_out]
print("x: ",X)
X_t = X[-forecast_out:]
df.dropna(inplace = True)
#print("X_lately: ",X_lately)
y =df['label']
#y.dropna(inplace=True)
y = py.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

x:  [[ 0.21957701  0.35158842  0.2438502   0.33902312  0.57003893]
 [ 0.333439    0.32609131  0.33003463  0.3135814   0.09418217]
 [ 0.31949692  0.28900494  0.3207176   0.31589428 -0.20978824]
 ..., 
 [ 1.58359974  1.62643234  1.55292517  1.64811528 -0.76520107]
 [ 1.75323099  1.80027469  1.78119853  1.77763653 -0.61862083]
 [ 1.80667699  1.81418185  1.80915008  1.81001736 -0.73690657]]


ValueError: Found input variables with inconsistent numbers of samples: [1726, 1744]

In [70]:
#y= np.array(df2['label'])

In [71]:
#print(len(X), len(y))

In [13]:
#X_train, X_test, y_train, y_test = cross_validation.train_test_split(X,y,test_size=0.2)
#X_train, X_test, y_train, y_test = train_test_split(X,y)  #split data into test and train
clf = LinearRegression() #use classifier as Linear Regression 
clf.fit(X_train, y_train)
forecast_set = clf.predict(X_test)
print(forecast_set)
accuracy =clf.score(, y_test)
print(accuracy)


[ 31.04250859  31.10294044  31.07159852  31.09607037  31.42341153
  31.29232218  29.40110035  29.82547435  29.78385035  29.66569796
  29.48602852  29.88833828  29.6137481   29.60927557  29.49686174
  29.32587464  29.11172647  29.2385852 ]
0.873641129741


In [73]:
#last_date=time.strptime(last_date, '%Y-%m-%d %H:%M:%S')


df['Forecast'] = np.nan
last_date = df.iloc[-1].date
last_date1= df.iloc[-1].name
print(last_date1)
print(last_date)
last_date_str=str(last_date)
last_date=d.strptime(last_date_str, '%Y-%m-%d %H:%M:%S')
last_date2= dt.date(last_date)
print("l:",last_date2)
x_1 = str(last_date2)
#x_label = int(x_1)
last_unix = last_date.timestamp()
print("last_unix: ",last_unix)
one_day = 86400
#one_day_seconds
next_unix = last_unix + one_day

for i in forecast_set:
    next_date = dt.fromtimestamp(next_unix)
    next_unix += one_day
    df.loc[next_date] = [py.nan for _ in range(len(df.columns)-1)]+[i]
#print(df.tail())

style.use('ggplot')
df['close'].plot()
df['Forecast'].plot()
#wl.scatter()
#ax.legend((line1,line2),('Actual','Predicted'))
wl.xlabel('Date')
wl.ylabel('Price')
wl.show()

[ 28.55927011  28.29597389  28.57457671  28.51334414  28.58399728
  28.44840825  28.47282885  28.75780974  27.85858487  27.16954627
  27.45212075  27.99964935  28.5224899   28.46746629  28.005529
  28.53576476  28.37600022]
193365
2016-07-07 00:00:00
l: 2016-07-07


ValueError: invalid literal for int() with base 10: '2016-07-07'